In [1]:
import numpy as np
import pandas as pd

## Getting the data

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv')
print(df.head())
print(df)

  Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         C

## Q3 : What's the average price of BMW cars in the dataset?

In [3]:
df_BMW = df[df['Make'] == 'BMW']
print('Average price of the BMW:', df_BMW['MSRP'].mean())

Average price of the BMW: 61546.76347305389


## Q4 : Select a subset of cars after year 2015. How many of them have missing values for Engine HP?

In [4]:
df_2015 = df[df['Year'] >= 2015]
print(df_2015['Engine HP'].isnull().sum())

51


## Q5 : Calculate the average "Engine HP" in the dataset.
##     Use the fillna method and to fill the missing values in "Engine HP" with the mean value from the previous step.
##     Now, calcualte the average of "Engine HP" again.
##     Has it changed?

In [5]:
mean_hp_before = df['Engine HP'].mean()
print('Engine HP with fillna values:', round(mean_hp_before, 2))

df['Engine HP fillna'] = df['Engine HP'].fillna(df['Engine HP'].mean())
mean_hp_after = df['Engine HP fillna'].mean()
print('Engine HP without fillna values:', round(mean_hp_after, 2))

Engine HP with fillna values: 249.39
Engine HP without fillna values: 249.39


##  Q6 : Select all the "Rolls-Royce" cars from the dataset.
#     Select only columns "Engine HP", "Engine Cylinders", "highway MPG".
#     Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 7 rows).
#     Get the underlying NumPy array. Let's call it X.
#     Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
#     Invert XTX.
#     What's the sum of all the elements of the result?

In [6]:
X = np.array(df[df.Make == "Rolls-Royce"][["Engine HP", "Engine Cylinders", "highway MPG"]].drop_duplicates())
print(X)
print(X.shape)

XTX = X.T.dot(X)
print(XTX)

XTX_invert = np.linalg.inv(XTX)
print(XTX_invert.sum())

[[325.   8.  15.]
 [563.  12.  19.]
 [563.  12.  21.]
 [563.  12.  20.]
 [322.  12.  15.]
 [453.  12.  19.]
 [624.  12.  21.]]
(7, 3)
[[1.754801e+06 3.965600e+04 6.519600e+04]
 [3.965600e+04 9.280000e+02 1.500000e+03]
 [6.519600e+04 1.500000e+03 2.454000e+03]]
0.032212320677486125


## Q7 : Create an array y with values [1000, 1100, 900, 1200, 1000, 850, 1300].
##     Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
##     What's the value of the first element of w?.

In [7]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])
w = (XTX_invert.dot(X.T)).dot(y)
print(w[0])

0.19989598183189017
